class Cores {
  static int FLOATING_BUTTON_FOREGROUND = 0xFFBFD7EA;
  static int FLOATING_BUTTON_BACKGROUND = 0xFF931621;
  static int CARD_BACKGROUND = 0xFFDEF4C6;
  static int FONTE_CARD_DELETE_SIM = 0xFFFF1111;
  static int FONTE_CARD_DELETE_CANCELAR = 0xFE0000FE;
  static int APPBAR = 0XFF931621;
}
