class Cores {
  static int FLOATING_BUTTON_FOREGROUND = 0xFFBFD7EA;
  static int FLOATING_BUTTON_BACKGROUND = 0xFFFF9B42;
  static int CARD_BACKGROUND = 0xFFEDDEA4;
  static int FONTE_CARD_DELETE_SIM = 0xFFFF1111;
  static int FONTE_CARD_DELETE_CANCELAR = 0xFE0000FE;
}
